/**
 * Assignment management server actions — Milestone 2.
 *
 * Security guarantees:
 * - organization_id and teacher_id are derived from authenticated server context.
 * - share_token is generated server-side (URL-safe, cryptographically random).
 * - class_id is validated to belong to the authenticated teacher.
 * - Assignment status transitions are enforced server-side.
 * - RLS policies on `assignments` double-enforce all access.
 */
"use server";

import { createSupabaseServerClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";

export type AssignmentActionResult =
  | { ok: true; assignmentId?: string }
  | { ok: false; error: string };

// ── Actions ───────────────────────────────────────────────────────────────────

/**
 * createAssignment — creates a new draft assignment.
 *
 * organization_id and teacher_id are derived from the authenticated session.
 * The client cannot supply or override these fields.
 * A URL-safe share_token is generated by the database via generate_share_token().
 */
export async function createAssignment(
  classId: string,
  formData: FormData
): Promise<AssignmentActionResult> {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) return { ok: false, error: "not_authenticated" };

  const title = (formData.get("title") as string | null)?.trim() ?? "";
  const instructions = (formData.get("instructions") as string | null)?.trim() ?? null;
  const deadlineRaw = (formData.get("submission_deadline") as string | null)?.trim() ?? null;
  const creativePrompt =
    (formData.get("creative_intent_prompt") as string | null)?.trim() ||
    "Explain the creative choices behind your photograph.";

  if (!title) return { ok: false, error: "title_required" };
  if (title.length > 200) return { ok: false, error: "title_too_long" };

  const submissionDeadline = deadlineRaw ? new Date(deadlineRaw).toISOString() : null;

  // Verify teacher owns this class and get organization_id
  const { data: cls, error: clsError } = await supabase
    .from("classes")
    .select("id, organization_id, teacher_id")
    .eq("id", classId)
    .eq("teacher_id", user.id)
    .maybeSingle();

  if (clsError || !cls) return { ok: false, error: "class_not_found" };

  // Generate share_token via DB function (server-side, not from client)
  const { data: tokenRow } = await supabase.rpc("generate_share_token" as any);
  const shareToken: string = tokenRow ?? crypto.randomUUID().replace(/-/g, "");

  const { data: assignment, error: insertError } = await supabase
    .from("assignments")
    .insert({
      organization_id: cls.organization_id,
      class_id: classId,
      teacher_id: user.id,
      title,
      instructions,
      creative_intent_prompt: creativePrompt,
      submission_deadline: submissionDeadline,
      share_token: shareToken,
      status: "draft",
    })
    .select("id")
    .single();

  if (insertError || !assignment) {
    console.error("[assignments] create failed:", insertError?.code);
    return { ok: false, error: "create_failed" };
  }

  redirect(`/classes/${classId}/assignments/${assignment.id}`);
}

/**
 * publishAssignment — transitions draft → accepting_submissions.
 */
export async function publishAssignment(
  assignmentId: string
): Promise<AssignmentActionResult> {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) return { ok: false, error: "not_authenticated" };

  const { data: assignment, error: fetchError } = await supabase
    .from("assignments")
    .select("id, status, class_id, teacher_id")
    .eq("id", assignmentId)
    .eq("teacher_id", user.id)
    .maybeSingle();

  if (fetchError || !assignment) return { ok: false, error: "assignment_not_found" };
  if (assignment.status !== "draft")
    return { ok: false, error: "invalid_transition" };

  const { error } = await supabase
    .from("assignments")
    .update({ status: "accepting_submissions" })
    .eq("id", assignmentId)
    .eq("teacher_id", user.id);

  if (error) return { ok: false, error: "update_failed" };
  return { ok: true, assignmentId };
}

/**
 * moveAssignmentToReview — transitions accepting_submissions → submission_review.
 */
export async function moveAssignmentToReview(
  assignmentId: string
): Promise<AssignmentActionResult> {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) return { ok: false, error: "not_authenticated" };

  const { data: assignment, error: fetchError } = await supabase
    .from("assignments")
    .select("id, status, teacher_id")
    .eq("id", assignmentId)
    .eq("teacher_id", user.id)
    .maybeSingle();

  if (fetchError || !assignment) return { ok: false, error: "assignment_not_found" };
  if (assignment.status !== "accepting_submissions")
    return { ok: false, error: "invalid_transition" };

  const { error } = await supabase
    .from("assignments")
    .update({ status: "submission_review" })
    .eq("id", assignmentId)
    .eq("teacher_id", user.id);

  if (error) return { ok: false, error: "update_failed" };
  return { ok: true, assignmentId };
}

/**
 * archiveAssignment — move to archived status from any terminal-eligible state.
 */
export async function archiveAssignment(
  assignmentId: string,
  classId: string
): Promise<AssignmentActionResult> {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) return { ok: false, error: "not_authenticated" };

  const { error } = await supabase
    .from("assignments")
    .update({ status: "archived" })
    .eq("id", assignmentId)
    .eq("teacher_id", user.id);

  if (error) return { ok: false, error: "update_failed" };
  redirect(`/classes/${classId}`);
}
